const data = {
  products: [
    {
      name: 'MuscleBlaze Beginners Protein, 2.2 lb, Chocolate flavor',
      slug: 'muscleblaze-beginner-protein',
      category: 'Whey Protein',
      image: '/images/mb-beginners-protein.jpg', // 679px × 829px
      price: 18,
      countInStock: 10,
      brand: 'MuscleBlaze',
      rating: 4.5,
      numReviews: 1003,
      description:
        'An optimum dose of 12g of protein with zero added sugar in each serving. Made from the best source of protein Whey. As a top-notch beginners protein, it ensures quick absorption, increase in muscle growth and curbs hunger pangs by improving satiety',
    },
    {
      name: 'BSN Syntha-6, 5 lb, Chocolate Milkshake',
      slug: 'bsn-syntha-6',
      category: 'Whey Protein',
      image: '/images/bsn-syntha-6.jpg',
      price: 76,
      countInStock: 0,
      brand: 'BSN',
      rating: 5,
      numReviews: 1493,
      description:
        ' A unique blend of fast and slow digesting proteins that can be taken ANYTIME to support muscle protein synthesis and recove, What Does It Have - 22 grams protein per serving including 10 g of naturally occurring EAAs with 6g Fiber, & MCT.',
    },
    {
      name: 'MuscleBlaze High Protein Peanut Butter, 0.750 kg, Dark Chocolate Creamy',
      slug: 'muscleblaze-high-protein-peanut',
      category: 'Peanut Butter',
      image: '/images/mb-high-protein-peanut-butter.jpg',
      price: 6,
      countInStock: 15,
      brand: 'Muscleblaze',
      rating: 4.5,
      numReviews: 487,
      description:
        'Exotic & delectable dark chocolate meets creamy and nutritious peanut butter to give you a heavenly experience of snacking. With 27g protein this product is a great source of protein for fulfilling your daily protein needs',
    },
    {
      name: 'MB Fuel One Mass Gainer Immunity+ , 1.6 lb, Chocolate flavor',
      slug: 'muscleblaze-fuel-one-mass-gainer',
      category: 'Mass gainer',
      image: '/images/mb-fuel-gainer.jpg',
      price: 11,
      countInStock: 5,
      brand: 'Muscleblaze',
      rating: 4.5,
      numReviews: 569,
      description:
        'MB Fuel One Mass Gainer Immunity+ is a special formula that is more than just a mass gainer. It helps in boosting your immunity levels along with letting you have a healthy weight gain',
    },
    {
      name: 'Labrada Muscle Mass, 6.61 lb',
      slug: 'labrada-muscle-mass-gainer',
      category: 'Mass gainer',
      image: '/images/labrada-muscle-mass.jpg',
      price: 47,
      countInStock: 11,
      brand: 'Labrada',
      rating: 4.3,
      numReviews: 782,
      description:
        'Labrada Muscle Mass Gainer 6 lb Chocolate helps to supply protein and other essential nutrients for muscle growth. It aids to provide right calories for weight gain and helps in building your muscle tone and mass',
    },
    {
      name: 'Oatein High Protein Oats, 1 kg, Dark Milk Chocolate flavor',
      slug: 'oatein-high-protein-oats',
      category: 'Oats',
      image: '/images/oatein-oats.jpg',
      price: 7,
      countInStock: 7,
      brand: 'Muscleblaze',
      rating: 3.9,
      numReviews: 347,
      description:
        '17 g PROTEIN PER SERVING: Oatein High Protein Oats with Probiotics provides 17 g protein per serving with 250 ml of skimmed milk. Feel satiated for longer with satisfying protein in each spoonful',
    },
    {
      name: 'ON (Optimum Nutrition) Gold 100% Whey Protein, 5 lb, Double Chocolate',
      slug: 'on-gold-standard-whey-protein',
      category: 'Whey Protein',
      image: '/images/optimum-whey-protein.jpg',
      price: 90,
      countInStock: 3,
      brand: 'Optimum Nutrition',
      rating: 5,
      numReviews: 2663,
      description: `Gold Standard 100% Whey Blend - 24g blended protein consisting of whey protein isolate, whey protein concentrate, and whey peptides/hydrolysates to support muscle recovery. Primary protein source is Isolate, they dont call it the Gold Standard of quality for nothing.`,
    },
    {
      name: 'MuscleBlaze Biozyme Performance Whey, 8.8 lb, Rich Chocolate',
      slug: 'muscleblaze-biozyme-performance-whey',
      category: 'Whey Protein',
      image: '/images/mb-bioenzyme-whey.jpg',
      price: 110,
      countInStock: 21,
      brand: 'Muscleblaze',
      rating: 4.5,
      numReviews: 432,
      description:
        'WINNER, PRODUCT OF THE YEAR, SPORTS NUTRITION at the NutraIngredients Award 2021 in Singapore. Testimony of the research, quality & innovation behind the Biozyme series. ENHANCED ABSORPTION FORMULA (EAF ®) in MB Biozyme Performance Whey ensures 50% HIGHER PROTEIN ABSORPTION & 60% SUPERIOR BCAA ABSORPTION compared to other whey proteins.',
    },
    {
      name: 'MuscleBlaze High Protein Muesli, 1 kg, Dark Rich Chocolate & Cranberry Cream flavor',
      slug: 'muscleblaze-high-protein-muesli',
      category: 'Protein Muesli',
      image: '/images/mb-protein-muesli.jpg',
      price: 8,
      countInStock: 10,
      brand: 'Muscleblaze',
      rating: 4.0,
      numReviews: 235,
      description:
        'POWER OF PROTEIN: This high protein muesli provides 25g protein per 100g that helps keep you satiated for longer GOODNESS OF GRAIN: Rolled oats, rolled barley, quinoa puffs & brown rice flakes are rich in fibre, protein, minerals, and antioxidants making this high protein muesli a nutritious breakfast or snack',
    },
    {
      name: 'Myfitness Chocolate Peanut Butter, 1.250 kg, Crunchy',
      slug: 'myfitness-chocolate-peanut-butter',
      category: 'Peanut Butter',
      image: '/images/myfitness-peanut-butter.jpg',
      price: 7,
      countInStock: 11,
      brand: 'Muscleblaze',
      rating: 3.5,
      numReviews: 673,
      description:
        'Our delicious chocolate peanut butter spread contains unsweetened Belgian dark chocolate! This is in addition to the fact that it already contains the good kind of brown sugar and pink Himalayan salt',
    },
  ],
};
export default data;
